### ISSUE TITLE
traceBlock API error

### ISSUE THREAD

**Issue by jeongkyun-oh** [klaytn/klaytn#1193]
Baobab node will panic when calling traceAPI with `callTracer`.
Only calling traceBlock API without `callTracer` was fine. Also, it was fine to call with `fastCallTracer` tracer.

Simply calling an API will trigger the error.
```
> debug.traceBlockByNumber(83179868, {tracer: "callTracer"})
Error: EOF
    at web3.js:3276:20
    at web3.js:6450:15
    at web3.js:5214:36
    at <anonymous>:1:1
```

Log
```
SIGABRT: abort
PC=0x7fdd42a07ae0 m=78 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fdd42a07ae0
stack: frame={sp:0x7fdaae7c6ab0, fp:0x0} stack=[0x7fdaadffc288,0x7fdaae7fbe88)
00007fdaae7c69b0:  000000001ab3a4c7  00000000017da534
00007fdaae7c69c0:  0000000000000070  00007fdcb80fb230
00007fdaae7c69d0:  00007fdba42bc060  00007fdba42bc07b
00007fdaae7c69e0:  00000000000006ef  0000000000000001
00007fdaae7c69f0:  0000000000000000  00000000017e7ce5
00007fdaae7c6a00:  00007fdba42bc07b  00000000017e7ebf
00007fdaae7c6a10:  6e65206e6f736a27  6365722065646f63
00007fdaae7c6a20:  6c206e6f69737275  0000002774696d69
00007fdaae7c6a30:  00007fdaae7c6b20  00007fdcb80d0fe0
00007fdaae7c6a40:  000000000000001b  00007fdd42a52308
00007fdaae7c6a50:  00007fdaae7c6c00  00007fdd42d76100
00007fdaae7c6a60:  0000000000000000  0000000000000032
00007fdaae7c6a70:  000000040000003c  0000000000000007
00007fdaae7c6a80:  0000000000000040  cf335a4531535f00
00007fdaae7c6a90:  00007fdaae7c6ad0  00007fdaae7c6ad0
00007fdaae7c6aa0:  000000000000007f  0000000001ffd804
00007fdaae7c6ab0: <0000000000000000  00007fdaae7fbb40
00007fdaae7c6ac0:  00007fdaae7c6d20  00007fdd42a46e10
00007fdaae7c6ad0:  00000000fbad8001  00007fdaae7c6d20
00007fdaae7c6ae0:  00007fdaae7c6d20  00007fdaae7c6d20
00007fdaae7c6af0:  00007fdaae7c6d20  00007fdaae7c6d47
00007fdaae7c6b00:  00007fdaae7c6d9f  00007fdaae7c6d20
00007fdaae7c6b10:  00007fdaae7c6d9f  0000000000000000
00007fdaae7c6b20:  0000000000000000  0000000000000000
00007fdaae7c6b30:  fffffffe7fffffff  ffffffffffffffff
00007fdaae7c6b40:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b50:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b60:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b70:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b80:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b90:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6ba0:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7fdd42a07ae0
stack: frame={sp:0x7fdaae7c6ab0, fp:0x0} stack=[0x7fdaadffc288,0x7fdaae7fbe88)
00007fdaae7c69b0:  000000001ab3a4c7  00000000017da534
00007fdaae7c69c0:  0000000000000070  00007fdcb80fb230
00007fdaae7c69d0:  00007fdba42bc060  00007fdba42bc07b
00007fdaae7c69e0:  00000000000006ef  0000000000000001
00007fdaae7c69f0:  0000000000000000  00000000017e7ce5
00007fdaae7c6a00:  00007fdba42bc07b  00000000017e7ebf
00007fdaae7c6a10:  6e65206e6f736a27  6365722065646f63
00007fdaae7c6a20:  6c206e6f69737275  0000002774696d69
00007fdaae7c6a30:  00007fdaae7c6b20  00007fdcb80d0fe0
00007fdaae7c6a40:  000000000000001b  00007fdd42a52308
00007fdaae7c6a50:  00007fdaae7c6c00  00007fdd42d76100
00007fdaae7c6a60:  0000000000000000  0000000000000032
00007fdaae7c6a70:  000000040000003c  0000000000000007
00007fdaae7c6a80:  0000000000000040  cf335a4531535f00
00007fdaae7c6a90:  00007fdaae7c6ad0  00007fdaae7c6ad0
00007fdaae7c6aa0:  000000000000007f  0000000001ffd804
00007fdaae7c6ab0: <0000000000000000  00007fdaae7fbb40
00007fdaae7c6ac0:  00007fdaae7c6d20  00007fdd42a46e10
00007fdaae7c6ad0:  00000000fbad8001  00007fdaae7c6d20
00007fdaae7c6ae0:  00007fdaae7c6d20  00007fdaae7c6d20
00007fdaae7c6af0:  00007fdaae7c6d20  00007fdaae7c6d47
00007fdaae7c6b00:  00007fdaae7c6d9f  00007fdaae7c6d20
00007fdaae7c6b10:  00007fdaae7c6d9f  0000000000000000
00007fdaae7c6b20:  0000000000000000  0000000000000000
00007fdaae7c6b30:  fffffffe7fffffff  ffffffffffffffff
00007fdaae7c6b40:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b50:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b60:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b70:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b80:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6b90:  ffffffffffffffff  ffffffffffffffff
00007fdaae7c6ba0:  ffffffffffffffff  ffffffffffffffff

goroutine 273746962 [syscall]:
runtime.cgocall(0x17ca370, 0xc0b62d79c8, 0xc0b62d7900)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0b62d7998 sp=0xc0b62d7960 pc=0x415e7b
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_json_encode(0x7fdcb80fb230, 0xc0ffffffff, 0x0)
        _cgo_gotypes.go:2189 +0x4e fp=0xc0b62d79c8 sp=0xc0b62d7998 pc=0x154860e
gopkg.in/olebedev/go-duktape%2ev3.(*Context).JsonEncode.func1(0xc07dcb6370, 0xffffffffffffffff, 0x7fdb00000000)
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20181125150206-ccb656ba24c2/api.go:749 +0x68 fp=0xc0b62d7a00 sp=0xc0b62d79c8 pc=0x1559668
gopkg.in/olebedev/go-duktape%2ev3.(*Context).JsonEncode(0xc07dcb6370, 0xffffffffffffffff, 0x2, 0x0)
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20181125150206-ccb656ba24c2/api.go:749 +0x35 fp=0xc0b62d7a28 sp=0xc0b62d7a00 pc=0x154f735
github.com/klaytn/klaytn/node/cn/tracers.(*Tracer).call(0xc015d2c9a0, 0x1c743de, 0x6, 0xc0b62d7b90, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/rpmbuild/BUILD/kend-v1.7.3/node/cn/tracers/tracer.go:524 +0x205 fp=0xc0b62d7aa0 sp=0xc0b62d7a28 pc=0x1565185
github.com/klaytn/klaytn/node/cn/tracers.(*Tracer).GetResult(0xc015d2c9a0, 0x1fa8f00, 0xc085d8d7c0, 0x0, 0x0, 0x0)
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/rpmbuild/BUILD/kend-v1.7.3/node/cn/tracers/tracer.go:649 +0x458 fp=0xc0b62d7c20 sp=0xc0b62d7aa0 pc=0x15664f8
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceTx(0xc010f235d0, 0x1f8d0e0, 0xc07020b400, 0x1fa8f00, 0xc085d8d7c0, 0x1d1c468, 0x1d1c478, 0xc045d61dd0, 0xac378f28f5228a62, 0xb2216db1e740c92b, ...)
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/rpmbuild/BUILD/kend-v1.7.3/node/cn/api_tracer.go:821 +0x692 fp=0xc0b62d7d78 sp=0xc0b62d7c20 pc=0x15d9072
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock.func1(0xc0712b8710, 0xc071291860, 0xc0362fc5a8, 0x1, 0x1, 0x1f9bf40, 0xc046a56110, 0xc01ab8a700, 0xc014dc4628, 0x1, ...)
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/rpmbuild/BUILD/kend-v1.7.3/node/cn/api_tracer.go:511 +0x610 fp=0xc0b62d7f68 sp=0xc0b62d7d78 pc=0x1603350
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0b62d7f70 sp=0xc0b62d7f68 pc=0x482f61
created by github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock
        /go/src/github.com/klaytn/klaytn/ken-linux-x86_64/rpmbuild/BUILD/kend-v1.7.3/node/cn/api_tracer.go:497 +0x4bf
...
```

**Comment by jeongkyun-oh** [comment]
Related Ethereum PR - https://github.com/ethereum/go-ethereum/issues/16426, https://github.com/ethereum/go-ethereum/issues/21879
