### ISSUE TITLE
v1.8.0-rc.1 HandleGovernanceVote panic

### ISSUE THREAD

**Issue by jeongkyun-oh** [klaytn/klaytn#1194]
While syncing cypress network with `v1.8.0-rc.1`, the following panic occurred. On 75038593 (2021/11/13 - when cypress network crashed), a node cannot handle the governance vote. Calling API `istanbul.getSnapshot(75038593)` will trigger the panic as well.

```
goroutine 766 [running]:
github.com/klaytn/klaytn/governance.(*Governance).HandleGovernanceVote(0xc0193906c0, 0x2030f00, 0xc04e3fac80, 0xc04e4c83c0, 0x1, 0x1, 0xc2aba42d20, 0x1, 0x1, 0xc04a67d200, ...)
        /ext-go/3/src/github.com/klaytn/klaytn/governance/handler.go:344 +0x47a
github.com/klaytn/klaytn/consensus/istanbul/backend.(*Snapshot).apply(0xc116949800, 0xc169d31b68, 0x1, 0x1, 0xc0193906c0, 0xee622d9b9d780512, 0xe9416d734190c4d8, 0x9b257ea3, 0x2, 0x201e840, ...)
        /ext-go/3/src/github.com/klaytn/klaytn/consensus/istanbul/backend/snapshot.go:194 +0x328
github.com/klaytn/klaytn/consensus/istanbul/backend.(*backend).snapshot(0xc00015a840, 0x201e840, 0xc00072b400, 0x478ff80, 0x872de7c9d0162107, 0xa205bd843958cd7a, 0xf2692c05ead79ed, 0xdca4b02b8a630a70, 0x0, 0x0, ...)
        /ext-go/3/src/github.com/klaytn/klaytn/consensus/istanbul/backend/engine.go:705 +0x3f2
github.com/klaytn/klaytn/consensus/istanbul/backend.(*backend).CreateSnapshot(0xc00015a840, 0x201e840, 0xc00072b400, 0x478ff81, 0xdadf62b0fd09eb5b, 0xae056901f4759267, 0x3698887cf4dc508, 0x349293bb988a1765, 0x0, 0x0, ...)
        /ext-go/3/src/github.com/klaytn/klaytn/consensus/istanbul/backend/engine.go:659 +0x9a
github.com/klaytn/klaytn/blockchain.(*BlockChain).insertChain(0xc00072b400, 0xc133f06000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/3/src/github.com/klaytn/klaytn/blockchain/blockchain.go:1980 +0x29de
github.com/klaytn/klaytn/blockchain.(*BlockChain).InsertChain(0xc00072b400, 0xc133f06000, 0x800, 0x800, 0x0, 0x0, 0x8)
        /ext-go/3/src/github.com/klaytn/klaytn/blockchain/blockchain.go:1691 +0x67
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).importBlockResults(0xc00011f860, 0xc133e1c000, 0x800, 0x800, 0x800, 0x0)
        /ext-go/3/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:1423 +0x539
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).processFullSyncContent(0xc00011f860, 0x0, 0x0)
        /ext-go/3/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:1397 +0x10a
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync.func1(0xc00011f860, 0xc0226fe420, 0xc0215f3670)
        /ext-go/3/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:506 +0x5b
created by github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync
        /ext-go/3/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:506 +0x16f
```

**Comment by yoomee1313** [comment]
the address length checking logic at `ParseVoteValue` which is added at https://github.com/klaytn/klaytn/pull/1110 caused this panic. 

"governance.addvalidator" votes around block 75038593 has data at "header.voteData", and when handling this voteData, the vote.Data has 42 bytes. However, it should have 20 bytes. I tried to find out how 42 bytes came in (because the value should be address), but it was not successful.

The solution could be remove out the address length checking logic, because it is hard-fork.
