### ISSUE TITLE
Investigation of SetHead usage & bug

### ISSUE THREAD

**Issue by hqjang-pepper** [klaytn/klaytn#1235]
PR https://github.com/klaytn/klaytn/pull/1052/ version of setHead function will be used in klaytn v1.8.
Accordingly, I analyzed about usability comparison with the previous setHead version and current bugs.

1. usage - There are 2 difference between each version.
- If the block number does not have a state, it rewinds a bit more with the number that has state.
- With the new repair logic, it is now possible to decide whether to delete the block body after rewinding chain.

Functions that use sethead are as follow, usage and analysis results are as follows.
- NewBlockChain - headed to blockNum 0 since it's new blockchain. No changes compare to previous version.
- SetCanonicalBlock - rewinds blockchain when state is missing. 
- ResetWithGenesisBlock - head to 0. Logic of aiming genesis block is same.

2. bug 
fix PR : https://github.com/klaytn/klaytn/pull/1316
```
homi-output-CN-0-1        | INFO[03/10,16:02:40 Z] [5|blockchain/blockchain.go:2176]               Imported new chain segment                number=612 hash=30786f…ece037 blocks=192 txs=0 elapsed=365.531ms trieDBSize=69.56kB mgas=0.000 mgasps=0.000 age=20s323ms
homi-output-CN-0-1        | panic: runtime error: invalid memory address or nil pointer dereference
homi-output-CN-0-1        | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13094c4]
homi-output-CN-0-1        |
homi-output-CN-0-1        | goroutine 184 [running]:
homi-output-CN-0-1        | github.com/klaytn/klaytn/blockchain/types.(*Block).NumberU64(...)
homi-output-CN-0-1        | 	/go/src/github.com/klaytn/klaytn/blockchain/types/block.go:292
homi-output-CN-0-1        | github.com/klaytn/klaytn/blockchain.(*TxPool).reset(0xc00000c1e0, 0xc01706f680, 0xc01706f8c0)
homi-output-CN-0-1        | 	/go/src/github.com/klaytn/klaytn/blockchain/tx_pool.go:381 +0x244
homi-output-CN-0-1        | github.com/klaytn/klaytn/blockchain.(*TxPool).loop(0xc00000c1e0)
homi-output-CN-0-1        | 	/go/src/github.com/klaytn/klaytn/blockchain/tx_pool.go:294 +0x485
homi-output-CN-0-1        | created by github.com/klaytn/klaytn/blockchain.NewTxPool
homi-output-CN-0-1        | 	/go/src/github.com/klaytn/klaytn/blockchain/tx_pool.go:246 +0x4da
```

**Comment by hqjang-pepper** [comment]
error analysis and fix PR : https://github.com/klaytn/klaytn/pull/1316

**Comment by hqjang-pepper** [comment]
Fix PR is merged, close this PR.
