### ISSUE TITLE
kscnd met panic

### ISSUE THREAD

**Issue by egonspace** [klaytn/klaytn#1466]
**Describe the bug**
KSCN process was unexpectedly down with the error log below.
Subbridge and anchoring was enabled, and no tx was sent to the chain when an incident occurred.

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

Here is log
```
WARN[06/20,08:42:52 Z] [45] initial value transfer recovery is failed  err="context deadline exceeded"
ERROR[06/20,08:42:52 Z] [45] setting remote bridge info is failed      err="write pipe: i/o timeout"
INFO[06/20,08:42:52 Z] [45] stop bridge loop                          addr=0x9c39a2af2b3c15E638dE6191A7651ae36C1232C1 onChildChain=true
INFO[06/20,08:42:52 Z] [45] stop bridge loop                          addr=0x9AEca73FF61A84067f08F580a5233fc7085EAa34 onChildChain=false
INFO[06/20,08:42:52 Z] [45] VT : Parent -> Child Chain                request=1 handle=1 lowerHandle=1 pending=0
INFO[06/20,08:42:52 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/20,08:42:52 Z] [45] stop bridge loop                          addr=0x9365e2decA6c2978C0815831e2daBaE2d01a0613 onChildChain=true
INFO[06/20,08:42:52 Z] [45] Regenerated local transaction journal     transactions=1 accounts=1
INFO[06/20,08:42:52 Z] [45] BridgeTxPool loop is closing
INFO[06/20,08:42:52 Z] [45] Transaction pool stopped
panic: close of closed channel

goroutine 236 [running]:
github.com/klaytn/klaytn/node/sc.(*BridgeManager).DeleteBridgeInfo(0xc000232c60, 0xc05564c15b4169a8, 0x3dadb6ad311d27c3, 0xc0e4a4fb30, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/node/sc/bridge_manager.go:610 +0xc6
github.com/klaytn/klaytn/node/sc.(*BridgeManager).RestoreBridges(0xc000232c60, 0xc001187f40, 0x2)
        /ext-go/1/src/github.com/klaytn/klaytn/node/sc/bridge_manager.go:682 +0xc45
github.com/klaytn/klaytn/node/sc.(*SubBridge).restoreBridgeLoop(0xc000250680)
        /ext-go/1/src/github.com/klaytn/klaytn/node/sc/subbridge.go:594 +0x1ab
created by github.com/klaytn/klaytn/node/sc.(*SubBridge).SetComponents
        /ext-go/1/src/github.com/klaytn/klaytn/node/sc/subbridge.go:379 +0x3bc
```

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
 - go version `$ go version`
 - OS and its version [e.g. macOS/10.14]

Klaytn version: Klaytn v1.8.2 (Installed via kscn-v1.8.2-0-linux-amd64.tar.gz in [Download](https://ko.docs.klaytn.foundation/node/download/v1.8.2) page.
OS: Amazon Linux 2 Kernel 5.10 AMI 2.0.20220426.0 x86_64 HVM gp2

**Additional context**

**Comment by hyunsooda** [comment]
Thanks for the report. The error path shown seems rare. I think its error path could not have happened if you did not stop the node manually (i.e., `kscnd stop`). 

 Would you check out the questions below?
- Did you had a misconfiguration? For example, the ports `SC_SUB_BRIDGE_PORT` and `SC_MAIN_BRIDGE_PORT` opened normally, but not the `RPC_PORT`? On this misconfiguration, did you stop the node? 

Could you additionally put the front part of the logs you put?

**Comment by egonspace** [comment]
- We didn't `stop kscnd` or even `kill` the daemon.
- all port configuration is normal
  - SC_SUB_BRIDGE = 1
  - SC_SUB_BRIDGE_PORT = 50505
  - PORT=32323
  - RPC_PORT=8551
- What's unusual about the log is that many messages below were taken.
```
INFO[06/20,08:42:18 Z] [45] VT : Parent -> Child Chain                request=1 handle=1 lowerHandle=1 pending=0
INFO[06/20,08:42:18 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/20,08:42:18 Z] [45] VT : Parent -> Child Chain                request=1 handle=1 lowerHandle=1 pending=0
INFO[06/20,08:42:18 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
...
(repeated many times)
INFO[06/20,08:42:18 Z] [45] Generate an anchoring tx                  blockNum=2327400 blockhash=0x01b1dfaba34e1b363328a2fbcac0f9cc4f1582bd61fb79798bd2ad9bc26da047 txCount=0 txHash=0xc12632dae81d3ab5ad6be692c496a7925dd39e299701600d3f49d197e06df0f3
INFO[06/20,08:42:18 Z] [45] VT : Parent -> Child Chain                request=1 handle=1 lowerHandle=1 pending=0
INFO[06/20,08:42:18 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
(repeated many times)
...
INFO[06/20,08:42:24 Z] [33] Added a multichannel P2P Peer             id=7f0f892d6d6240c5 conn=inbound    peerID=7f0f892d6d6240c5
WARN[06/20,08:42:30 Z] [25] [RC] timeoutEvent Sent!                   set by=startNewRound sequence=2331281 round=0 proposer=0x6586c79c56765143a50B9d239f5E0c01e4a70D19 preprepare is nil?=true len(prepares)=0 len(commits)=0
WARN[06/20,08:42:30 Z] [25] [RC] Prepare messages received before catchUpRound  address=0xb46591BbE24dc3A3480F2048Ee32b5741DBf6DaF state="Accept request" len(prepares)=0 messages="\n"
WARN[06/20,08:42:30 Z] [25] [RC] Commit messages received before catchUpRound  address=0xb46591BbE24dc3A3480F2048Ee32b5741DBf6DaF state="Accept request" len(commits)=0 messages="\n"
WARN[06/20,08:42:30 Z] [25] [RC] Catch up round                       address=0xb46591BbE24dc3A3480F2048Ee32b5741DBf6DaF old_round=0 old_seq=2331281 old_proposer=0x6586c79c56765143a50B9d239f5E0c01e4a70D19 new_round=1 new_seq=2331281 new_proposer=0x6586c79c56765143a50B9d239f5E0c01e4a70D19
...
INFO[06/20,08:42:45 Z] [18] Got interrupt, shutting down...    // we didn't send any signal
INFO[06/20,08:42:45 Z] [5] Inserted a new block                      number=2331297 hash=9acc5f…94e701 txs=0 gas=0 elapsed=550.805µs processTxs=168ns finalize=28.033µs  validateState=3.105µs   totalWrite=319.619µs   trieWrite=107.332µs
INFO[06/20,08:42:45 Z] [40] WebSocket endpoint closed                 url=ws://0.0.0.0:8552
INFO[06/20,08:42:45 Z] [40] HTTP endpoint closed                      url=http://0.0.0.0:8551
INFO[06/20,08:42:45 Z] [40] IPC endpoint closed                       endpoint=/home/ec2-user/data/klay.ipc
INFO[06/20,08:42:45 Z] [45] value transfer recovery is already stopped
INFO[06/20,08:42:45 Z] [50] Commit new mining work                    number=2331298 hash=841fd1…591f11 txs=0 elapsed=49.354µs  commitTime=26.386µs finalizeTime=19.899µs
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/misc
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/header
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/body
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/receipts
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/statetrie
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/txlookup
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/bridgeservice
INFO[06/20,08:42:45 Z] [47] Database closed                           path=/home/ec2-user/data/klay/subbridgedata/snapshot
WARN[06/20,08:42:52 Z] [45] initial value transfer recovery is failed  err="context deadline exceeded"
ERROR[06/20,08:42:52 Z] [45] setting remote bridge info is failed      err="write pipe: i/o timeout"
INFO[06/20,08:42:52 Z] [45] stop bridge loop                          addr=0x9c39a2af2b3c15E638dE6191A7651ae36C1232C1 onChildChain=true
INFO[06/20,08:42:52 Z] [45] stop bridge loop                          addr=0x9AEca73FF61A84067f08F580a5233fc7085EAa34 onChildChain=false
INFO[06/20,08:42:52 Z] [45] VT : Parent -> Child Chain                request=1 handle=1 lowerHandle=1 pending=0
INFO[06/20,08:42:52 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/20,08:42:52 Z] [45] stop bridge loop                          addr=0x9365e2decA6c2978C0815831e2daBaE2d01a0613 onChildChain=true
INFO[06/20,08:42:52 Z] [45] Regenerated local transaction journal     transactions=1 accounts=1
INFO[06/20,08:42:52 Z] [45] BridgeTxPool loop is closing
INFO[06/20,08:42:52 Z] [45] Transaction pool stopped
panic: close of closed channel

```

**Comment by hyunsooda** [comment]
When I saw the error for the first time, the error path shown was really strange. Now, I have a little bit of confirmation through your additional logs. The node might be self-tearing down by interrupt (`SIGINT` and `SIGTERM`). 

The reason why I said the error could not have happened without node kill is that I thought there's must be only one possible path, that is, node kill (do close channel for the first time) with subsequently failed bridge re-setup (another close call of that already closed channel if it's failed). 

Consequently, the panic of `closed of closed channel` is definitely an error and I uploaded the fix at #1471. You may not know who sent the `SIGINT` and `SIGTERM` to the `kscn` process. If it's not the first time, could you let me know how to reproduce its unexpected exit by an unknown signal? Also, the system call tracer `strace` may be attached to your running `kscn` process and can trace the received signals.

**Comment by egonspace** [comment]
I heard from another team member that there is a possibility that they might have restarted at that time. If it happens again, I will write the information here. I think you can solve this issue for now. Thank you so much.

By the way, isn't there any particular problem with this log being taken repeatedly?
```
INFO[06/29,05:36:12 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:36:12 Z] [45] VT : Parent -> Child Chain                request=1 handle=1 lowerHandle=1 pending=0
```

**Comment by hyunsooda** [comment]
That log shows a brief status of value transfer between chains. When you make a value transfer transaction, you can see the `request` field would be increased. This log is repeatedly printed every one second approximately (precisely, when a block of child chain is newly mined)

**Comment by egonspace** [comment]
I mean, it's not repeated every second, it's a lot of the same logs in a short period of time.
```
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Parent -> Child Chain                request=0 handle=0 lowerHandle=0 pending=0
INFO[06/29,05:53:11 Z] [45] VT : Child -> Parent Chain                request=0 handle=0 lowerHandle=0 pending=0
...
```

**Comment by hyunsooda** [comment]
No, it's not expected to print a lot at the same time. Could you put the preceding and subsequent logs you put? Or, you can link the full log file through Google drive.

**Comment by hyunsooda** [comment]
I asked to figure the configuration out again and you said all the was fine,  
`Did you had a misconfiguration? For example, the ports SC_SUB_BRIDGE_PORT and SC_MAIN_BRIDGE_PORT opened normally, but not the RPC_PORT? On this misconfiguration, did you stop the node?`

So I requested additional logs, but I [found there's another possible case](https://github.com/klaytn/klaytn/issues/1466#issuecomment-1169551369). Anyway, if you encounter any error or bugs, please directly CC @hyunsooda and @2dvorak to easily track them. Thank you.

**Comment by hyunsooda** [comment]
> I think the reason why this log was taken a lot is because it is in the chain syncing.

Now it makes sense why the unexpected repeated logs were printed. As I mentioned, that log is printed at every block event.

-------
I say this just out of concern for you, If your purpose of work in ServiceChain is highly devoted in Value Transfer, please remind two important security aspects.
1. **DO NOT OPEN SUBBRIDGE RPC SERVICE TO PUBLIC AND ENDPOINT ADDRESS OF THE KSCN NODE.** The some of APIs in subbridge module are privileged APIs. If you have need of RPC call of subbridge module APIs, you must do them in IPC(console) for now.   
2. **DO NOT OPEN BRIDGE CONTRACT ADDRESS TO PUBLIC**. If you should service value transfer between chains, the recommended way is to make its process to black-box manner. No user must be able to make a value transfer transaction themselves. Actually, the trusted anchor of value transfer is bridge contract and operator. Thus, every user must be able to send value transfer transaction at any time without any further permission. However, the current design and implementation did not consider the possible security holes of their public usage. We are now working to establish secure value transfer without loss of public usage.

cc. @2dvorak
