### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by gitmewai** [klaytn/klaytn#1560]
**Describe the bug**
We encountered several occurrences of the following error after upgraded from `v1.8.1` to `v1.8.4` (and still the same after downgrade back to `v1.8.1`)

On node #1:
```
INFO[07/24,08:32:39 Z] [41] Regenerating historical state             block=96442241 target=96442291 remaining=50  elapsed=594ns
INFO[07/24,08:32:39 Z] [41] Historical state regenerated              block=96442291 elapsed=26.125027ms  nodeSize=56.90kB  preimageSize=1.50kB
panic: runtime error: slice bounds out of range [:-1]
```

On node #2:
```
INFO[07/24,05:48:37 Z] [41] Regenerating historical state             block=96530817 target=96530934 remaining=117 elapsed=814ns
INFO[07/24,05:48:37 Z] [41] Historical state regenerated              block=96530934 elapsed=132.199644ms nodeSize=118.39kB preimageSize=4.89kB
panic: runtime error: slice bounds out of range [:-8070450532247928833]
```

**How to reproduce**
1. upgrade the node from `v1.8.1` to `v1.8.4`
2. downgrade the node from `v1.8.4` back to `v1.8.1`

**Expected behavior**
Should not encounter the panic errors.

**Attachments**

On node #1:
```
INFO[07/24,08:32:39 Z] [41] Regenerating historical state             block=96442241 target=96442291 remaining=50  elapsed=594ns
INFO[07/24,08:32:39 Z] [41] Historical state regenerated              block=96442291 elapsed=26.125027ms  nodeSize=56.90kB  preimageSize=1.50kB
panic: runtime error: slice bounds out of range [:-1]

goroutine 1299234 [running]:
github.com/klaytn/klaytn/blockchain/vm.(*Memory).Slice(...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/memory.go:143
github.com/klaytn/klaytn/blockchain/vm.(*InternalTxTracer).step(0xc09f616be0, 0xc0c89f0b38, 0xc154f1df60, 0xc0c89f0b90)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/internaltx_tracer.go:289 +0x26d8
github.com/klaytn/klaytn/blockchain/vm.(*InternalTxTracer).CaptureState(0xc09f616be0, 0xc154f321a0, 0x8d, 0xc154f2d2f1, 0x5dda647, 0x5c62fb9, 0xc154f2d220, 0xc154f2d240, 0xc154f32340, 0x2, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/internaltx_tracer.go:217 +0x185
github.com/klaytn/klaytn/blockchain/vm.(*Interpreter).Run(0xc154d651f0, 0xc154f32340, 0xc152b36740, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/interpreter.go:315 +0x737
github.com/klaytn/klaytn/blockchain/vm.run(0xc154f321a0, 0xc154f32340, 0xc152b36740, 0x24, 0x40, 0xf3, 0x100, 0x1cf9349bd19d46cb, 0x1, 0xa4)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:90 +0x8a
github.com/klaytn/klaytn/blockchain/vm.(*EVM).Call(0xc154f321a0, 0x2005220, 0xc154f32270, 0x2d58f382fe8999a0, 0xcde3acaa08aa2556, 0xc117bd8217, 0xc152b36740, 0x24, 0x40, 0x5dda717, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:277 +0x665
github.com/klaytn/klaytn/blockchain/vm.opCall(0xc154d03f68, 0xc154f321a0, 0xc154f32270, 0xc154f2d0c0, 0xc154f2d0e0, 0x5dda9d3, 0xc154f2d0c0, 0xc154f2d0e0, 0xc154f32270, 0x1)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/instructions.go:755 +0x2e5
github.com/klaytn/klaytn/blockchain/vm.(*Interpreter).Run(0xc154d651f0, 0xc154f32270, 0xc1525733b0, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/interpreter.go:320 +0x536
github.com/klaytn/klaytn/blockchain/vm.run(0xc154f321a0, 0xc154f32270, 0xc1525733b0, 0x24, 0x24, 0x1b72084f64461405, 0x100, 0xc1525733b0, 0x24, 0x24)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:90 +0x8a
github.com/klaytn/klaytn/blockchain/vm.(*EVM).Call(0xc154f321a0, 0x2005160, 0xc154f20330, 0x844550f9735af3d9, 0x644614053e857720, 0x1b72084f, 0xc1525733b0, 0x24, 0x24, 0x5f580e8, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:277 +0x665
github.com/klaytn/klaytn/blockchain/types.(*TxInternalDataSmartContractExecution).Execute(0xc001ad47e0, 0x2005160, 0xc154f20330, 0x20102a0, 0xc154f321a0, 0x2033fa0, 0xc12c255980, 0x5bf97b4, 0x5f580e8, 0xc154f2cf20, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/tx_internal_data_smart_contract_execution.go:329 +0x13a
github.com/klaytn/klaytn/blockchain/types.(*Transaction).Execute(0xc0b165cc60, 0x20102a0, 0xc154f321a0, 0x2033fa0, 0xc12c255980, 0x5bf97b4, 0x5f580e8, 0xc154f2cf20, 0x70, 0x1c3d9a0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/transaction.go:508 +0x193
github.com/klaytn/klaytn/blockchain.(*StateTransition).TransitionDb(0xc154d65260, 0x203a840, 0xc0b165cc60, 0xc154d65260, 0xc154f321a0, 0x1c3e340, 0xc005eda001, 0xc154f2ce80)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/state_transition.go:267 +0x193
github.com/klaytn/klaytn/blockchain.ApplyMessage(0xc154f321a0, 0x203a840, 0xc0b165cc60, 0xd5afcb688882b86b, 0x83fee7307e1ac775, 0xa61be350, 0xc154f2ce60, 0x9efe97a3def94fb7, 0x2afe53eb45f51d23, 0xb26c77df)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/state_transition.go:160 +0x53
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceTx(0xc000e78ef0, 0x201c3a0, 0xc0bab2b680, 0x203a840, 0xc0b165cc60, 0x1da1be8, 0x1da1bf8, 0xc154d632f0, 0xd5afcb688882b86b, 0x83fee7307e1ac775, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:806 +0x2b4
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock.func1(0xc154b2d0d0, 0xc15495b3e0, 0xc151ae4c30, 0x2, 0x2, 0x202f100, 0xc154459cd0, 0xc1529ce540, 0xc154459ce0, 0x2, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:511 +0x610
created by github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:497 +0x4bf
```

On node #2:
```
INFO[07/24,05:48:37 Z] [41] Regenerating historical state             block=96530817 target=96530934 remaining=117 elapsed=814ns
INFO[07/24,05:48:37 Z] [41] Historical state regenerated              block=96530934 elapsed=132.199644ms nodeSize=118.39kB preimageSize=4.89kB
panic: runtime error: slice bounds out of range [:-8070450532247928833]

goroutine 9772 [running]:
github.com/klaytn/klaytn/blockchain/vm.(*Memory).Slice(...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/memory.go:143
github.com/klaytn/klaytn/blockchain/vm.(*InternalTxTracer).step(0xc09e092460, 0xc0009e0b38, 0xc0a1aa4180, 0xc0009e0b90)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/internaltx_tracer.go:289 +0x26d8
github.com/klaytn/klaytn/blockchain/vm.(*InternalTxTracer).CaptureState(0xc09e092460, 0xc0a0fbaa90, 0x8d, 0xc0a1a9acf1, 0x5dda683, 0x5c62ff4, 0xc0a1a9acc0, 0xc0a1a9ace0, 0xc0a0fbac30, 0x2, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/internaltx_tracer.go:217 +0x185
github.com/klaytn/klaytn/blockchain/vm.(*Interpreter).Run(0xc0a0ffe5b0, 0xc0a0fbac30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/interpreter.go:315 +0x737
github.com/klaytn/klaytn/blockchain/vm.run(0xc0a0fbaa90, 0xc0a0fbac30, 0x0, 0x0, 0x0, 0xf3, 0x100, 0x2eda23212b002a8e, 0x1, 0x80)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:90 +0x8a
github.com/klaytn/klaytn/blockchain/vm.(*EVM).Call(0xc0a0fbaa90, 0x2005220, 0xc0a0fbab60, 0xf14ee995087fd9e0, 0xae07dfdaa931fe4b, 0x7fbdfb9eb437, 0x0, 0x0, 0x0, 0x5dda747, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:277 +0x665
github.com/klaytn/klaytn/blockchain/vm.opCall(0xc0a0fc5658, 0xc0a0fbaa90, 0xc0a0fbab60, 0xc0a1a9ab60, 0xc0a1a9ab80, 0x5ddaa03, 0xc0a1a9ab60, 0xc0a1a9ab80, 0xc0a0fbab60, 0x1)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/instructions.go:755 +0x2e5
github.com/klaytn/klaytn/blockchain/vm.(*Interpreter).Run(0xc0a0ffe5b0, 0xc0a0fbab60, 0xc09e46a120, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/interpreter.go:320 +0x536
github.com/klaytn/klaytn/blockchain/vm.run(0xc0a0fbaa90, 0xc0a0fbab60, 0xc09e46a120, 0x24, 0x24, 0x3c2cc3990e810b28, 0x100, 0xc09e46a120, 0x24, 0x24)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:90 +0x8a
github.com/klaytn/klaytn/blockchain/vm.(*EVM).Call(0xc0a0fbaa90, 0x2005160, 0xc0a0fe6570, 0x7cbfe7eb1f5db140, 0xe810b28cb31c9ed, 0x3c2cc399, 0xc09e46a120, 0x24, 0x24, 0x5f580e8, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/vm/evm.go:277 +0x665
github.com/klaytn/klaytn/blockchain/types.(*TxInternalDataSmartContractExecution).Execute(0xc0071de750, 0x2005160, 0xc0a0fe6570, 0x20102a0, 0xc0a0fbaa90, 0x2033fa0, 0xc0a0226600, 0x5c0f1f7, 0x5f580e8, 0xc0a1a9a9c0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/tx_internal_data_smart_contract_execution.go:329 +0x13a
github.com/klaytn/klaytn/blockchain/types.(*Transaction).Execute(0xc000670b00, 0x20102a0, 0xc0a0fbaa90, 0x2033fa0, 0xc0a0226600, 0x5c0f1f7, 0x5f580e8, 0xc0a1a9a9c0, 0x70, 0x1c3d9a0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/transaction.go:508 +0x193
github.com/klaytn/klaytn/blockchain.(*StateTransition).TransitionDb(0xc0a0ffe620, 0x203a840, 0xc000670b00, 0xc0a0ffe620, 0xc0a0fbaa90, 0x1c3e340, 0xc001f63801, 0xc0a1a9a920)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/state_transition.go:267 +0x193
github.com/klaytn/klaytn/blockchain.ApplyMessage(0xc0a0fbaa90, 0x203a840, 0xc000670b00, 0x542b6afa5434115a, 0x97f9df603fa55208, 0xe001f800, 0xc0a1a9a900, 0x44dcd0cbdca7b15c, 0x2088de8e8940366e, 0xc8548536)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/state_transition.go:160 +0x53
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceTx(0xc002dfae60, 0x201c3a0, 0xc09e3bdb00, 0x203a840, 0xc000670b00, 0x1da1be8, 0x1da1bf8, 0xc0a0f8bbf0, 0x542b6afa5434115a, 0x97f9df603fa55208, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:806 +0x2b4
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock.func1(0xc0a1d073f0, 0xc0a10bb800, 0xc006f53f90, 0x2, 0x2, 0x202f100, 0xc09fc019e0, 0xc09de47960, 0xc09fc019f0, 0x2, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:511 +0x610
created by github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:497 +0x4bf
```

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
```
ken version
Klaytn v1.8.1+275b47b11e
```
(Note: both v1.8.1 and v1.8.4 obtained from http://packages.klaytn.net/klaytn/v1.8.1/ken-v1.8.1-0-linux-amd64.tar.gz and http://packages.klaytn.net/klaytn/v1.8.4/ken-v1.8.4-0-linux-amd64.tar.gz respectively)

 - go version `$ go version`
Nil

 - OS and its version [e.g. macOS/10.14]
```
$ cat /etc/debian_version 
10.12
$ uname -a
Linux klaytn-2 4.19.0-21-cloud-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
```

**Additional context**

**Comment by blukat29** [comment]
Hi @gitmewai, thanks for the report.

The version v1.9.0 contains relevant patches (https://github.com/klaytn/klaytn/pull/1527, https://github.com/klaytn/klaytn/pull/1549). The patches eliminate out-of-bound slice accesses in `blockchain/vm/memory.go`, which appears in your logs.

Could you check if it still crashes in v1.9.0 (https://github.com/klaytn/klaytn/releases/tag/v1.9.0)?

**Comment by aidan-kwon** [comment]
Resolved via https://github.com/klaytn/klaytn/pull/1527, https://github.com/klaytn/klaytn/pull/1549

**Comment by jiOnederfull** [comment]
Hi, @aidan-kwon
It occurs at `Klaytn v1.10.0+a7ac680ffc` as below
```
INFO[03/16,13:34:02 Z] [5] Inserted a new block                      number=117063194 hash=010aa6…59e1b1 txs=3     gas=4187712   elapsed=27.789ms  processTxs=19.898ms  finalize=1.930ms   validateState=453.997µs totalWrite=4.645433ms   trieWrite=4.460872ms
panic: runtime error: slice bounds out of range [:4344] with capacity 4096

goroutine 475082996 [running]:
bufio.(*Reader).Read(0xc1063b95c0, 0xc01d837799, 0x867, 0x867, 0x16a0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:238 +0x3ba
github.com/valyala/fasthttp.(*requestStream).Read(0xc095373bf0, 0xc01d837799, 0x867, 0x867, 0x16a0, 0x0, 0x0)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/streaming.go:75 +0x45e
github.com/valyala/bytebufferpool.(*ByteBuffer).ReadFrom(0xc26087a560, 0x20e6e00, 0xc095373bf0, 0x7fedd0ca3890, 0xc26087a560, 0x41ef01)
	/go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/bytebuffer.go:45 +0xf2
io.copyBuffer(0x20e6c40, 0xc26087a560, 0x20e6e00, 0xc095373bf0, 0xc0860a0000, 0x1000, 0x1000, 0x0, 0x1, 0x0)
	/usr/local/go/src/io/io.go:395 +0x2ff
io.CopyBuffer(0x20e6c40, 0xc26087a560, 0x20e6e00, 0xc095373bf0, 0xc0860a0000, 0x1000, 0x1000, 0x42b285, 0x421785, 0x42b285)
	/usr/local/go/src/io/io.go:382 +0x8c
github.com/valyala/fasthttp.copyZeroAlloc(0x20e6c40, 0xc26087a560, 0x20e6e00, 0xc095373bf0, 0xc0fafaec30, 0x0, 0xc000700000)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/http.go:1981 +0xa7
github.com/valyala/fasthttp.(*Request).bodyBytes(0xc10891d600, 0xc09785e5d8, 0x78603f, 0x1c21de0)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/http.go:371 +0xca
github.com/valyala/fasthttp.(*Request).Body(0xc10891d600, 0x7ffa2a7007d0, 0xc0ff105400, 0x7f3774)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/http.go:671 +0x110
github.com/valyala/fasthttp.(*RequestCtx).PostBody(...)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:1415
github.com/valyala/fasthttp/fasthttpadaptor.ConvertRequest(0xc10891d600, 0xc000241e98, 0x1, 0xc14e1f6f60, 0x6)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/fasthttpadaptor/request.go:15 +0x45
github.com/valyala/fasthttp/fasthttpadaptor.NewFastHTTPHandler.func1(0xc10891d600)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/fasthttpadaptor/adaptor.go:50 +0x98
github.com/valyala/fasthttp.TimeoutWithCodeHandler.func1.1(0xc098b82420, 0xc10891d600, 0xc12af57920, 0xc0987ac060)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:471 +0x30
created by github.com/valyala/fasthttp.TimeoutWithCodeHandler.func1
	/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:470 +0xe8
```

I wanted to let you know just in case since now the node works well after the restart.
