### ISSUE TITLE
SC: stopping during subbridge shutdown

### ISSUE THREAD

**Issue by jeonghonah** [klaytn/klaytn#24]
**Describe the bug**
- A phenomenon that can no longer proceed if the bridge subscription exists in the subbridge during shutdown.

**How to reproduce**

- Setup service chain
- Deploy bridge contract and subscribe
- Shutdown (simply kill <PID>)
- get stuck

**Expected behavior**
Stopped at callstack as shown below:

```
goroutine 3336 [select, 2 minutes]:
 github.com/klaytn/klaytn/networks/rpc.(*requestOp).wait(0xc0b4ee1400, 0x515ff60, 0xc0000b4008, 0xc0b4ee1400, 0x4d99260, 0xc0b4f06e70)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:143 +0xce
 github.com/klaytn/klaytn/networks/rpc.(*Client).CallContext(0xc0002163f0, 0x515ff60, 0xc0000b4008, 0x4cac2a0, 0xc0b4cf3e40, 0xc0b4e8cf90, 0x10, 0xc0b4cf3e50, 0x1, 0x1, ...)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:312 +0x1fc
 github.com/klaytn/klaytn/networks/rpc.(*Client).Call(0xc0002163f0, 0x4cac2a0, 0xc0b4cf3e40, 0xc0b4e8cf90, 0x10, 0xc0b4cf3e50, 0x1, 0x1, 0x3, 0xc0a11c9e00)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:287 +0x9f
 github.com/klaytn/klaytn/networks/rpc.(*ClientSubscription).requestUnsubscribe(0xc0b4500990, 0x28, 0xa)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:835 +0x12d
 github.com/klaytn/klaytn/networks/rpc.(*ClientSubscription).quitWithError.func1()
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:764 +0x11d
 sync.(*Once).Do(0xc0b45009e8, 0xc0b133fb70)
     /usr/local/go/src/sync/once.go:44 +0xb3
 github.com/klaytn/klaytn/networks/rpc.(*ClientSubscription).quitWithError(0xc0b4500990, 0x0, 0x0, 0xae14101)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:758 +0x75
 github.com/klaytn/klaytn/networks/rpc.(*ClientSubscription).Unsubscribe(0xc0b4500990)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/networks/rpc/client.go:753 +0x38
 github.com/klaytn/klaytn/contracts/bridge.(*BridgeFilterer).WatchRequestValueTransfer.func1(0xc0b4294c60, 0x0, 0x0)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/contracts/bridge/Bridge.go:1331 +0x4d5
 github.com/klaytn/klaytn/event.NewSubscription.func1(0xc0b44dff20, 0xc0b44f01e0)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/event/subscription.go:56 +0x65
 created by github.com/klaytn/klaytn/event.NewSubscription
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/event/subscription.go:54 +0xc2

 goroutine 3785 [chan receive, 2 minutes]:
 github.com/klaytn/klaytn/event.(*funcSub).Unsubscribe(0xc0b44dff20)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/event/subscription.go:86 +0x99
 github.com/klaytn/klaytn/event.(*SubscriptionScope).Close(0xc00011e698)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/event/subscription.go:256 +0xd6
 github.com/klaytn/klaytn/node/sc.(*BridgeManager).Stop(0xc00011e580)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/node/sc/bridge_manager.go:936 +0x106
 github.com/klaytn/klaytn/node/sc.(*SubBridge).Stop(0xc0000b9ba0, 0x0, 0x0)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/node/sc/subbridge.go:728 +0xe8
 github.com/klaytn/klaytn/node.(*Node).Stop(0xc000122580, 0x0, 0x0)
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/node/node.go:593 +0x1de
 created by github.com/klaytn/klaytn/cmd/utils.StartNode.func1
     /Users/jeongho/go/src/github.com/klaytn/klaytn-albert/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/cmd.go:54 +0x140
```

**Attachments**
n/a

**Environment (please complete the following information)**
- Klaytn v1.0.0+5ba9ed1168
- go version go1.12.5 darwin/amd64
- macOS/10.14.5

**Additional context**
n/a

**Comment by jeonghonah** [comment]
Currently, a remote backend and its `scope(event.SubscriptionScope)` is not working for shutdown. I'm looking at the relevant code.
