### ISSUE TITLE
SIGSEGV occurs when running ken without options

### ISSUE THREAD

**Issue by jeonghonah** [klaytn/klaytn#39]
**Describe the bug**
SIGSEGV occurs when $DATADIR is created with genesis that does not have governance field. This is not a common use case, but the program should exit as normal as possible.

**How to reproduce**
- ken init with wrong genesis file (e.g. without gevernance field), use default DATADIR.
- run ken without any options.

**Expected behavior**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4764394]

goroutine 1 [running]:
github.com/klaytn/klaytn/blockchain.SetupGenesisBlock(0x520a100, 0xc0002094a0, 0x0, 0x2019, 0x520a100, 0xc0002094a0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/blockchain/genesis.go:223 +0x944
github.com/klaytn/klaytn/node/cn.New(0xc00000e400, 0xc00018fb00, 0x4e79ac0, 0x4ee0301, 0xc00000e400)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/node/cn/backend.go:158 +0xef
github.com/klaytn/klaytn/cmd/utils.RegisterCNService.func1(0xc00000e400, 0xc000208e10, 0xc0003eb520, 0xc000208e10, 0x30)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/flags.go:1202 +0x62
github.com/klaytn/klaytn/node.(*Node).initService(0xc000402000, 0xc00062e050, 0x1, 0x1, 0xc000208e10, 0x2, 0x5e7b5e0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/node/node.go:292 +0xfd
github.com/klaytn/klaytn/node.(*Node).Start(0xc000402000, 0x0, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/node/node.go:202 +0x57f
github.com/klaytn/klaytn/cmd/utils.StartNode(0xc000402000)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/cmd.go:45 +0x2f
github.com/klaytn/klaytn/cmd/utils/nodecmd.startNode(0xc0001be160, 0xc000402000)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/nodecmd/defaultcmd.go:68 +0x7e
github.com/klaytn/klaytn/cmd/utils/nodecmd.RunKlaytnNode(0xc0001be160, 0x0, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/nodecmd/defaultcmd.go:56 +0x43
github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x4d72620, 0x4fecb48, 0xc0001be160, 0xc0001be160, 0xc0003ebf28)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0006341a0, 0xc0000e6000, 0x1, 0x1, 0x0, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x590
main.main()
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/ken/main.go:258 +0x12d
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49817be]

goroutine 1 [running]:
github.com/klaytn/klaytn/governance.(*Governance).ReadGovernance(0xc0001e2420, 0x0, 0xc0001da5e0, 0x1, 0x4, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/governance/default.go:523 +0x2e
github.com/klaytn/klaytn/governance.(*Governance).initializeCache(0xc0001e2420, 0x0, 0xc0001eefc0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/governance/default.go:443 +0xee
github.com/klaytn/klaytn/governance.NewGovernance(0xc00008ce40, 0x520a1e0, 0xc00057fce0, 0xc0001c4ba0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/governance/default.go:218 +0x29d
github.com/klaytn/klaytn/node/cn.New(0xc0005785c0, 0xc0003ae000, 0x4e79bc0, 0x4ee0401, 0xc0005785c0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/node/cn/backend.go:175 +0x2d3
github.com/klaytn/klaytn/cmd/utils.RegisterCNService.func1(0xc0005785c0, 0xc00057f5f0, 0xc0003df520, 0xc00057f5f0, 0x30)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/flags.go:1202 +0x62
github.com/klaytn/klaytn/node.(*Node).initService(0xc0001b0b00, 0xc000010020, 0x1, 0x1, 0xc00057f5f0, 0x2, 0x7612368)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/node/node.go:292 +0xfd
github.com/klaytn/klaytn/node.(*Node).Start(0xc0001b0b00, 0x0, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/node/node.go:202 +0x57f
github.com/klaytn/klaytn/cmd/utils.StartNode(0xc0001b0b00)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/cmd.go:45 +0x2f
github.com/klaytn/klaytn/cmd/utils/nodecmd.startNode(0xc000192840, 0xc0001b0b00)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/nodecmd/defaultcmd.go:68 +0x7e
github.com/klaytn/klaytn/cmd/utils/nodecmd.RunKlaytnNode(0xc000192840, 0x0, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/utils/nodecmd/defaultcmd.go:56 +0x43
github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x4d72720, 0x4fecc10, 0xc000192840, 0xc000192840, 0xc000503f28)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000da340, 0xc0000c0000, 0x3, 0x3, 0x0, 0x0)
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x590
main.main()
        /Users/jeongho/go/src/github.com/klaytn/klaytn/build/_workspace/src/github.com/klaytn/klaytn/cmd/ken/main.go:258 +0x12d

```
**Attachments**
n/a

**Environment (please complete the following information)**
 - Klaytn v1.0.0+5ba9ed1168
- go version go1.12.5 darwin/amd64
- macOS/10.14.5

**Additional context**
n/a

**Comment by KlaytnDev** [comment]
<details><summary>Builds ready [1aca7b1]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kcn-v1.0.1~rc.1-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kpn-v1.0.1~rc.1-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/ken-v1.0.1~rc.1-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kscn-v1.0.1~rc.1-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kspn-v1.0.1~rc.1-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/ksen-v1.0.1~rc.1-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kbn-v1.0.1~rc.1-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kgen-v1.0.1~rc.1-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/homi-v1.0.1~rc.1-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kcn-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kpn-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/ken-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kscn-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kspn-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/ksen-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kbn-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kgen-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/homi-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kcn-baobab-v1.0.1~rc.1-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kpn-baobab-v1.0.1~rc.1-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/ken-baobab-v1.0.1~rc.1-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kcn-baobab-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/kpn-baobab-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.0.1~rc.1/ken-baobab-v1.0.1~rc.1-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>
