### ISSUE TITLE
Please see bug report. 

### ISSUE THREAD

**Issue by MegaSolar** [klaytn/klaytn#435]
OS: virtual box CENTOS 7
version :Klaytn/v1.3.0/linux-amd64/go1.13.3"
Network: Baobab
Node Type: Endpoint
 Snapshot : https://s3.ap-northeast-2.amazonaws.com/klaytn-chaindata/baobab/klaytn-baobab-chaindata-20200108010112.tar.gz

**Attachments**
```
INFO[01/08,19:51:57 +09] [44] Add a new stakingInfo to the stakingInfoCache  stakingInfo="{\"BlockNum\":16848000,\"CouncilNodeAddrs\":[\"0x9     9fb17d324fa0e07f23b49d09028ac0919414db6\",\"0x571e53df607be97431a5bbefca1dffe5aef56f4d\",\"0xb74ff9dea397fe9e231df545eb53fe2adf776cb2\",\"0x     5cb1a7dccbd0dc446e3640898ede8820368554c8\",\"0x776817c0ef3d06d794cf01ae9afa33d7397b9b40\",\"0xc180ca565b34b5b63877674f5fe647e7da079022\",\"0     x03497f51c31fe8b402df0bde90fd5a85f87aa943\"],\"CouncilStakingAddrs\":[\"0x12fa1ab4c3e17c1c08c1b5a945c864c8e8bf707e\",\"0xfd56604f1a20268ff7a     0eab2ab48e25ee1e0f653\",\"0x1e0f6aaa9baa6081dc4910a854eebf8854c262ab\",\"0x5e6988415ebe0f6b088f5a676003ba60f572875a\",\"0xbb44998c2af35b8fae     e694cffe216558056d747e\",\"0x68cba498b7175cde9de08fc2e85ad3e9c8caefa8\",\"0x98efb31eeccafe35d53a6926e2a54c0858d9eebc\"],\"CouncilRewardAddrs     \":[\"0xb2bd3178affccd9f9f5189457f1cad7d17a01c9d\",\"0x6559a7b6248b342bc11fbcdf9343212bbc347edc\",\"0x82829a60c6eac4e3e9d6ed00891c69e88537fd     4d\",\"0xa86fd667c6a340c53cc5d796ba84dbe1f29cb2f7\",\"0x6e22cbe2b8bbd1df9f1d3c8ebae6d7ff5414a734\",\"0x24e593fb29731e54905025c230727dc28d229     f77\",\"0x2b2a7a1d29a203f60e0a964fc64231265a49cd97\"],\"KIRAddr\":\"0x716f89d9bc333286c79db4ebb05516897c8d208a\",\"PoCAddr\":\"0x2bcf9d3e4a8     46015e7e3152a614c684de16f37c6\",\"UseGini\":true,\"Gini\":-1,\"CouncilStakingAmounts\":[5000000,5000000,5000000,5000000,5000000,5000000,5000     000]}"
 You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/klaytn/klaytn/issues
 index allocation went beyond available resultCache space
 /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:508
 goroutine 460 [running]:
 runtime/debug.Stack(0x48, 0x0, 0x0)
          /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
 222 runtime/debug.PrintStack()
 223         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
 224 github.com/klaytn/klaytn/common.Report(0xc0a21b39f8, 0x1, 0x1)
 225         /ext-go/1/src/github.com/klaytn/klaytn/common/debug.go:39 +0x1a5
 226 github.com/klaytn/klaytn/datasync/downloader.(*queue).reserveHeaders(0xc0000e7300, 0xc0a1fafe00, 0x80, 0xc0a21ac150, 0xc0000110a8, 0xc0a21ac     180, 0xc0a21ac1b0, 0x14467a0, 0x1448c88, 0x0, ...)
 227         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:508 +0x676
 228 github.com/klaytn/klaytn/datasync/downloader.(*queue).ReserveBodies(0xc0000e7300, 0xc0a1fafe00, 0x80, 0x0, 0xc0a1fafe00, 0x0, 0x0)
 229         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:460 +0x110
 230 github.com/klaytn/klaytn/datasync/downloader.(*Downloader).fetchParts(0xc0001da4e0, 0x160c400, 0xc0001d2240, 0xc000b1f620, 0xc0a21b3eb0, 0xc     000046070, 0xc0a21b3ea0, 0xc0a21b3f10, 0xc0a21b3f00, 0xc0a21b3ef0, ...)
 231         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:1145 +0x7a5
 232 github.com/klaytn/klaytn/datasync/downloader.(*Downloader).fetchBodies(0xc0001da4e0, 0x101cd28, 0x1a, 0xc0a2181080)
 233         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:969 +0x337
 234 github.com/klaytn/klaytn/datasync/downloader.(*Downloader).syncWithPeer.func4(0xc0a189d770, 0x0)
 235         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:467 +0x36
 236 github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync.func1(0xc0001da4e0, 0xc0a1e1bda0, 0xc0a21dda00)
 237         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:489 +0x63
 238 created by github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync
 239         /ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:489 +0x176
 240 #### BUG! PLEASE REPORT ####
```

I'm trying to operate EN with baobab blockchain snapshot as I mentioned, Then I got error above. 
please check and PLEASE reply that whether cypress has same issue or not.

**Comment by kjhman21** [comment]
@MegaSolar Could you please let us know your hardware specification?

**Comment by MegaSolar** [comment]
@kjhman21 Hello. 
first bug report I mentioned above hardware spec is below. 

CPU : 1
RAM :32G
SSD:500G

so , I changed hardware spec like below and conducted same action as I mentioned; trying EN node for operation. 
CPU : 8
RAM :32G
SSD:500G

Then I had bug log like this. 
```
INFO[01/09,19:43:52 +09] [5] Imported new chain segment                number=16897320 hash=764cdb…115eb6 blocks=181  txs=6   elapsed=1.267s    trieDBSize=62.87kB  mgas=1.318  mgasps=1.040
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/klaytn/klaytn/issues
index allocation went beyond available resultCache space
/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:508
goroutine 540 [running]:
runtime/debug.Stack(0x48, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/klaytn/klaytn/common.Report(0xc0a25d79f8, 0x1, 0x1)
	/ext-go/1/src/github.com/klaytn/klaytn/common/debug.go:39 +0x1a5
github.com/klaytn/klaytn/datasync/downloader.(*queue).reserveHeaders(0xc000192700, 0xc0a252e000, 0x80, 0xc0a25f2480, 0xc0000109e8, 0xc0a25f24b0, 0xc0a25f24e0, 0x14467a0, 0x1448c88, 0xc000183e80, ...)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:508 +0x676
github.com/klaytn/klaytn/datasync/downloader.(*queue).ReserveBodies(0xc000192700, 0xc0a252e000, 0x80, 0x0, 0xc0a252e000, 0x0, 0x0)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:460 +0x110
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).fetchParts(0xc00036f380, 0x160c400, 0xc000201ad0, 0xc002120420, 0xc0a25d7eb0, 0xc000046070, 0xc0a25d7ea0, 0xc0a25d7f10, 0xc0a25d7f00, 0xc0a25d7ef0, ...)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:1145 +0x7a5
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).fetchBodies(0xc00036f380, 0x101cd28, 0x23, 0xc0a2449140)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:969 +0x337
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).syncWithPeer.func4(0xc0a1a84770, 0x0)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:467 +0x36
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync.func1(0xc00036f380, 0xc0a26720c0, 0xc0a266f320)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:489 +0x63
created by github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:489 +0x176
#### BUG! PLEASE REPORT ####

```
I think this is same issue that I said above.

**Comment by kjhman21** [comment]
@MegaSolar I think 32GB RAM could not be sufficient for downloading. If possible, could you try this again with 64GB? Our test has been done with AWS m5.4xlarge for downloading with recent heavy transactions.

**Comment by MegaSolar** [comment]
@kjhman21 But In your docs klaytn hardware requirement is 32G isn't it?

**Comment by MegaSolar** [comment]
@kjhman21 Is it mandatory to use AWS m5.4xlarge for operation even in baobab network?

**Comment by MegaSolar** [comment]
@kjhman21  I will test again and let you know

**Comment by kjhman21** [comment]
> @kjhman21 But docs in klaytn hardware requirement is 32G isn't it?
> https://docs.klaytn.com/node/endpoint-node/system-requirements

Yes, it was. I'm not 100% sure, but it seems that recent heavy transactions need more hardware resources. We also encountered hardware resource problem with 32GB RAM recently.

We will also investigate hardware requirements and update the documentation based on the investigation. Thanks for letting us know.

**Comment by MegaSolar** [comment]
@kjhman21 I got what you said. 
My question is when users started to test EN even in baobab network , AWS m5.4xlarge is in necessary?
Baobab network blockchain snap shot and transactions volume in block is not so much, I mean small transaction.

**Comment by MegaSolar** [comment]
@kjhman21 I updated hardware spec, and 
I running ```./kend start ``` snapshot was same that I said above.
looks like `ken` running in successful. 
so while running ```ken``` I removed ```kend.out``` then ```./kend stop```.
it has been successfully stopped ```ken```.

then I restarted ```ken``` through command ``` ./kend start ```. 
Bug was appeared. 

Please see the log. 

````
goroutine 1096 [running]:
runtime/debug.Stack(0x48, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/klaytn/klaytn/common.Report(0xc0a26719f8, 0x1, 0x1)
	/ext-go/1/src/github.com/klaytn/klaytn/common/debug.go:39 +0x1a5
github.com/klaytn/klaytn/datasync/downloader.(*queue).reserveHeaders(0xc000150a00, 0xc0a2f430e0, 0x80, 0xc0a32923c0, 0xc000134430, 0xc0a32923f0, 0xc0a3292420, 0x14467a0, 0x1448c88, 0x1, ...)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:508 +0x676
github.com/klaytn/klaytn/datasync/downloader.(*queue).ReserveBodies(0xc000150a00, 0xc0a2f430e0, 0x80, 0x0, 0xc0a2f43000, 0x0, 0x0)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/queue.go:460 +0x110
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).fetchParts(0xc00047e9c0, 0x160c400, 0xc0001ebc60, 0xc000d3cc00, 0xc0a2671eb0, 0xc0002280e0, 0xc0a2671ea0, 0xc0a2671f10, 0xc0a2671f00, 0xc0a2671ef0, ...)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:1145 +0x7a5
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).fetchBodies(0xc00047e9c0, 0x101d6ae, 0x4d90b3, 0xc0a2f65f50)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:969 +0x337
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).syncWithPeer.func4(0xc00006d770, 0xaf7708)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:467 +0x36
github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync.func1(0xc00047e9c0, 0xc0a31d0e40, 0xc0a32e6500)
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:489 +0x63
created by github.com/klaytn/klaytn/datasync/downloader.(*Downloader).spawnSync
	/ext-go/1/src/github.com/klaytn/klaytn/datasync/downloader/downloader.go:489 +0x176
#### BUG! PLEASE REPORT ####
```

Hardware spec is below. 

```
cpu : 8
RAM: 64G
OS : virtualbox centos 7 
SSD: 500G 

```

**Comment by Jongsic** [comment]
I got same error on AWS m5.2xlarge, cypress, 1.3.0

I don't understand KEND use such huge memory. It just has under 20000000 blocks data. 

It's very small size chain data.

**Comment by KimKyungup** [comment]
@MegaSolar  @Jongsic Thanks for the report. I also reproduced this situation.
I will fix this issue as soon as possible.
